# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: dawg
  
steps:
- script: mvn clean test
  displayName: 'Build and Run Unit Tests'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '***/target/surefire-report/TEST-*.xml'
    testResultsFormat: 'Junit'
    failTaskOnMissingResultsFile: true
  displayName: "Publish Maven Test Result"
   
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
